Repository Funfunz/lumina-next, pull requests merged in 2024-08, with the labels that each got.

#38 CRUD actions fixed
  examples/vite-react/src/components/button/config.ts
  examples/vite-react/src/components/flex/config.ts
  examples/vite-react/src/components/grid/config.ts
  examples/vite-react/src/components/image/config.ts
  examples/vite-react/src/components/linkBox/config.ts
  examples/vite-react/src/components/text/config.ts
  examples/vite-react/src/components/title/config.ts
  examples/vite-react/src/data/pageData.ts
  examples/vite-react/src/luminaComponents/config.ts
  packages/lumina-core/src/components/modals/add/index.tsx
  packages/lumina-core/src/components/render/index.tsx
  packages/lumina-core/src/components/tabs/treeView/componentTree/index.tsx
  packages/lumina-core/src/components/tabs/treeView/index.tsx
  packages/lumina-core/src/components/tabs/treeView/treeBranch/index.tsx
  packages/lumina-core/src/context/handleModalsContext.tsx
  packages/lumina-core/src/models/editor-buttonModel.ts
Labels: New Feature

#30 feature/58-forms
  packages/lumina-core/package.json
  packages/lumina-core/src/components/form-components/checkbox/index.tsx
  packages/lumina-core/src/components/form-components/checkbox/styles.scss
  packages/lumina-core/src/components/form-components/demo.tsx
  packages/lumina-core/src/components/form-components/index.scss
  packages/lumina-core/src/components/form-components/input/index.tsx
  packages/lumina-core/src/components/form-components/input/styles.scss
  packages/lumina-core/src/components/form-components/radio-button/index.tsx
  packages/lumina-core/src/components/form-components/radio-button/styles.scss
  packages/lumina-core/src/components/form-components/slider/index.tsx
  packages/lumina-core/src/components/form-components/slider/styles.scss
  packages/lumina-core/src/components/form-components/switch-list/index.tsx
  packages/lumina-core/src/components/form-components/switch-list/styles.scss
  packages/lumina-core/src/components/form-components/textarea/index.tsx
  packages/lumina-core/src/components/form-components/textarea/styles.scss
  packages/lumina-core/src/components/sidebar/index.tsx
  packages/lumina-core/src/components/styles.scss
  packages/lumina-core/src/main.tsx
  packages/lumina-core/src/styles/theme/css/lumina/tokens.css
  pnpm-lock.yaml
Labels: New Feature

#60 bugfix/46-fix-edit-icon-on-linkbox-component
  packages/lumina-core/src/components/action-buttons/add/index.tsx
  packages/lumina-core/src/components/action-buttons/delete/index.tsx
  packages/lumina-core/src/components/action-buttons/edit/index.tsx
  packages/lumina-core/src/styles/theme/css/lumina/tokens.css
Labels: bug

#79 bugfix/76-Remove-all-routing-from-Lumina
  examples/vite-react/package.json
  examples/vite-react/src/App.tsx
  packages/lumina-core/package.json
  packages/lumina-core/src/main.tsx
  pnpm-lock.yaml
Labels: bug

#81 Search bar improvements
  packages/lumina-core/src/components/tabs/treeView/index.tsx
Labels: enhancement
