Repository Funfunz/lumina-next, pull requests merged in 2024-07, with the labels that each got.

#11 Feature/56 improve the tree view
  apps/lumina-core/src/components/button/buttons.module.scss
  apps/lumina-core/src/components/button/buttons.tsx
  apps/lumina-core/src/components/search/search.module.scss
  apps/lumina-core/src/components/search/search.tsx
  apps/lumina-core/src/components/showEdit/showEdit.tsx
  apps/lumina-core/src/components/sidebar/sidebar.module.scss
  apps/lumina-core/src/components/tabs/treeView/treeView.module.scss
  apps/lumina-core/src/components/tabs/treeView/treeView.tsx
  apps/lumina-core/src/components/tabs/treeView/treeviewHeader/treeviewHeader.module.scss
  apps/lumina-core/src/components/tabs/treeView/treeviewHeader/treeviewHeader.tsx
  apps/lumina-core/src/theme/css/lumina/tokens.css
  apps/lumina-core/src/theme/tokens/globals/color/button.json
Labels: enhancement

#13 feature/56-improve-the-tree-view-V2
  apps/lumina-core/src/components/lumina-action-buttons/add/lumina-add-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/menu/lumina-menu-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/move/lumina-move-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/visible/lumina-visible-component.tsx
  apps/lumina-core/src/components/lumina-modals/add/add-modal.tsx
  apps/lumina-core/src/components/showEdit/showEdit.tsx
  apps/lumina-core/src/components/tabs/treeView/treeView.tsx
Labels: enhancement

#14 feature/56-improve-the-tree-component
  apps/lumina-core/src/components/lumina-action-buttons/move/lumina-move-component.tsx
Labels: enhancement

#16 Feature/62 lumina file structure renaming
  apps/lumina-core/src/app/[[...slug]]/page.tsx
  apps/lumina-core/src/app/editor/[[...slug]]/page.tsx
  apps/lumina-core/src/components/flex/config.ts
  apps/lumina-core/src/components/grid/config.ts
  apps/lumina-core/src/components/grid/grid.tsx
  apps/lumina-core/src/components/image/image.tsx
  apps/lumina-core/src/components/linkBox/config.ts
  apps/lumina-core/src/components/linkBox/linkBox.tsx
  apps/lumina-core/src/components/linkBox/linkBoxInternalNested.tsx
  apps/lumina-core/src/components/linkBox/linkBoxInternalV2.tsx
  apps/lumina-core/src/components/linkBox/linkBoxV2.tsx
  apps/lumina-core/src/components/linkBox/linkBoxV5.tsx
  apps/lumina-core/src/components/lumina-action-buttons/add/lumina-add-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/delete/lumina-delete-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/edit/lumina-edit-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/menu/lumina-menu-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/move/lumina-move-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/visible/lumina-visible-component.tsx
  apps/lumina-core/src/components/lumina-button/lumina-button.module.scss
  apps/lumina-core/src/components/lumina-button/lumina-button.tsx
  apps/lumina-core/src/components/lumina-editor/lumina-editor.module.scss
  apps/lumina-core/src/components/lumina-editor/lumina-editor.tsx
  apps/lumina-core/src/components/lumina-modals/add/lumina-add-modal.tsx
  apps/lumina-core/src/components/lumina-modals/delete/lumina-delete-modal.tsx
  apps/lumina-core/src/components/lumina-modals/edit/lumina-edit-modal.tsx
  apps/lumina-core/src/components/lumina-modals/lumina-modals.module.scss
  apps/lumina-core/src/components/lumina-render/lumina-dynamicComponent.tsx
  apps/lumina-core/src/components/lumina-render/lumina-render.tsx
  apps/lumina-core/src/components/lumina-search/lumina-search.module.scss
  apps/lumina-core/src/components/lumina-search/lumina-search.tsx
  apps/lumina-core/src/components/lumina-showEdit/lumina-inputRenderer.tsx
  apps/lumina-core/src/components/lumina-showEdit/lumina-showEdit.module.scss
  apps/lumina-core/src/components/lumina-showEdit/lumina-showEdit.tsx
  apps/lumina-core/src/components/lumina-showEdit/readme.md
  apps/lumina-core/src/components/lumina-sidebar/lumina-sidebar.module.scss
  apps/lumina-core/src/components/lumina-sidebar/lumina-sidebar.tsx
  apps/lumina-core/src/components/lumina-tabs/pages/lumina-page.module.scss
  apps/lumina-core/src/components/lumina-tabs/pages/lumina-page.tsx
  apps/lumina-core/src/components/lumina-tabs/treeView/componentTree/lumina-componentTree.tsx
  apps/lumina-core/src/components/lumina-tabs/treeView/lumina-treeView.module.scss
  apps/lumina-core/src/components/lumina-tabs/treeView/lumina-treeView.tsx
  apps/lumina-core/src/components/lumina-tabs/treeView/treeBranch/lumina-treeBranch.module.scss
  apps/lumina-core/src/components/lumina-tabs/treeView/treeBranch/lumina-treeBranch.tsx
  apps/lumina-core/src/components/lumina-tabs/treeView/treeViewComponentTree/lumina-componentTree.tsx
  apps/lumina-core/src/components/lumina-tabs/treeView/treeviewHeader/lumina-treeViewHeader.module.scss
  apps/lumina-core/src/components/lumina-tabs/treeView/treeviewHeader/lumina-treeViewHeader.tsx
  apps/lumina-core/src/components/search/search.tsx
  apps/lumina-core/src/components/showEdit/showEdit.tsx
  apps/lumina-core/src/components/tabs/treeView/treeView.tsx
  apps/lumina-core/src/components/titleText/config.ts
  apps/lumina-core/src/components/titleText/titleText.module.scss
  apps/lumina-core/src/components/titleText/titleText.tsx
  apps/lumina-core/src/staticComponentsPath/index.ts
Labels: documentation, enhancement

#20 feature/52-create-the-button-component
  apps/lumina-core/src/components/lumina-action-buttons/add/lumina-add-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/delete/lumina-delete-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/edit/lumina-edit-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/menu/lumina-menu-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/move/lumina-move-component.tsx
  apps/lumina-core/src/components/lumina-action-buttons/visible/lumina-visible-component.tsx
  apps/lumina-core/src/components/lumina-button/lumina-button-models.tsx
  apps/lumina-core/src/components/lumina-button/lumina-button.module.scss
  apps/lumina-core/src/components/lumina-button/lumina-button.tsx
  apps/lumina-core/src/components/lumina-button/lumina-buttonContent/lumina-buttonContent.tsx
  apps/lumina-core/src/components/lumina-modals/add/lumina-add-modal.tsx
  apps/lumina-core/src/components/lumina-modals/delete/lumina-delete-modal.tsx
  apps/lumina-core/src/components/lumina-modals/edit/lumina-edit-modal.tsx
  apps/lumina-core/src/components/lumina-search/lumina-search.tsx
  apps/lumina-core/src/components/lumina-sidebar/lumina-sidebar.tsx
  apps/lumina-core/src/components/lumina-tabs/pages/lumina-page.tsx
  apps/lumina-core/src/components/lumina-tabs/treeView/lumina-treeView.module.scss
  apps/lumina-core/src/components/lumina-tabs/treeView/treeBranch/lumina-treeBranch.module.scss
  apps/lumina-core/src/components/lumina-tabs/treeView/treeviewHeader/lumina-treeViewHeader.module.scss
  apps/lumina-core/src/components/lumina-tabs/treeView/treeviewHeader/lumina-treeViewHeader.tsx
  package-lock.json
  package.json
Labels: enhancement

#18 Lumina Title component
  apps/lumina-core/src/components/lumina-modals/edit/lumina-edit-modal.tsx
  apps/lumina-core/src/components/lumina-title/lumina-title.module.scss
  apps/lumina-core/src/components/lumina-title/lumina-title.tsx
  apps/lumina-core/src/theme/css/lumina/tokens.css
  apps/lumina-core/src/theme/tokens/globals/size/font.json
Labels: New Feature

#23 feature/65 client side button component
  apps/lumina-core/src/client-components/button/button.module.css
  apps/lumina-core/src/client-components/button/button.tsx
  apps/lumina-core/src/client-components/button/config.ts
  apps/lumina-core/src/client-components/grid/grid.tsx
  apps/lumina-core/src/staticComponentsPath/index.ts
Labels: New Feature

#31 Add ESLint, Stylelint and Prettier
  .stylelintrc.json
  examples/vite-react/src/components/linkBox/LinkboxContext.tsx
  packages/eslint-config/package.json
  packages/lumina-core/.prettierrc
  packages/lumina-core/eslint.config.mjs
  packages/lumina-core/package.json
  packages/lumina-core/src/components/action-buttons/add/add-component.tsx
  packages/lumina-core/src/components/action-buttons/edit/edit-component.tsx
  packages/lumina-core/src/components/button/button-models.tsx
  packages/lumina-core/src/components/button/button.module.scss
  packages/lumina-core/src/components/editor-button/editor-button.module.scss
  packages/lumina-core/src/components/editor-button/editor-button.tsx
  packages/lumina-core/src/components/editor-button/inputRenderer.tsx
  packages/lumina-core/src/components/editor/editor.module.scss
  packages/lumina-core/src/components/menu-button/menu-button.module.scss
  packages/lumina-core/src/components/modals/add/add-modal.tsx
  packages/lumina-core/src/components/modals/edit/edit-modal.tsx
  packages/lumina-core/src/components/modals/modals.module.scss
  packages/lumina-core/src/components/search-bar/search-bar.module.scss
  packages/lumina-core/src/components/sidebar/sidebar.module.scss
  packages/lumina-core/src/components/sidebar/sidebar.tsx
  packages/lumina-core/src/components/styles.scss
  packages/lumina-core/src/components/tabs/pages/page.module.scss
  packages/lumina-core/src/components/tabs/treeView/treeBranch/treeBranch.module.scss
  packages/lumina-core/src/components/tabs/treeView/treeView.module.scss
  packages/lumina-core/src/components/tabs/treeView/treeviewHeader/treeViewHeader.module.scss
  packages/lumina-core/src/context/reducers/builderDataContext.ts
  packages/lumina-core/src/main.tsx
  packages/lumina-core/src/styles/LuminaIcon-v1.3/demo-files/demo.css
  packages/lumina-core/src/styles/LuminaIcon-v1.3/style.css
  packages/lumina-core/src/styles/LuminaIcon-v1.3/style.scss
  packages/lumina-core/src/styles/LuminaIcon-v1.3/variables.scss
  packages/lumina-core/src/styles/css-utils/helpers/spacing.scss
  packages/lumina-core/src/styles/index.scss
  packages/lumina-core/src/styles/scss-utils/config/z-index.scss
  packages/lumina-core/src/styles/theme/build.js
  packages/lumina-core/src/styles/theme/config/index.js
  packages/lumina-core/src/styles/theme/css/lumina/tokens.scss
  packages/lumina-docs/.prettierrc
  packages/lumina-docs/eslint.config.mjs
  packages/lumina-docs/package.json
  packages/lumina-docs/src/App.css
  packages/lumina-docs/src/App.tsx
  packages/lumina-docs/src/index.css
  packages/lumina-docs/src/stories/components/button.css
  packages/lumina-docs/src/stories/components/header.css
  packages/lumina-docs/src/stories/pages/Page.tsx
  packages/lumina-docs/src/stories/pages/page.css
  pnpm-lock.yaml
Labels: enhancement
